/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fohi


import fohi.config.Hierarchy
import kotlin.math.log

fun main(args: Array<String>) = Hierarchy().main(args)


